spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PSMS_db
    username: common_user
    password: common_user_pwd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # 开发时可用 update，生产建议 validate 或 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: user
      password: user_pwd
      roles: USER
